#pragma config(Sensor, in1,    expanderBattery, sensorAnalog)
#pragma config(Sensor, dgtl1,  leftShoot,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightShoot,     sensorQuadEncoder)
#pragma config(Motor,  port2,           flMotor,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           blMotor,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           frMotor,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           brMotor,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           launcher1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           launcher2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           launcher3,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           launcher4,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool shooter = false;
long shootSpeed = 0;
long avgBatValue;
long backupBatValue;
long expBat;

task main()
{
	while (true) {
		motor[flMotor] = vexRT[Ch3];
		motor[blMotor] = vexRT[Ch3];
		motor[frMotor] = vexRT[Ch2];
		motor[brMotor] = vexRT[Ch2];

		if (vexRT[Btn8D])
			shooter = true;
		if (vexRT[Btn7D])
			shooter = false;

		if (shooter && shootSpeed < 127)
			shootSpeed++;
		else if (shooter && !(shootSpeed < 127))
			shootSpeed = 127;
		else if (!shooter && shootSpeed > 0)
			shootSpeed--;
		else
			shootSpeed = 0;

		motor[launcher1] = shooter * shootSpeed;
		motor[launcher2] = shooter * shootSpeed;
		motor[launcher3] = shooter * shootSpeed;
		motor[launcher4] = shooter * shootSpeed;

		avgBatValue = nAvgBatteryLevel;
		backupBatValue = BackupBatteryLevel;
		expBat = SensorValue[expanderBattery] / 300;

		wait1Msec(10);
	}

}
