#pragma config(Sensor, in1,    expanderBattery, sensorAnalog)
#pragma config(Sensor, dgtl1,  leftShoot,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightShoot,     sensorQuadEncoder)
#pragma config(Motor,  port2,           flMotor,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           blMotor,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           frMotor,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           brMotor,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           launcherL1,    tmotorVex393_MC29, openLoop, encoderPort, dgtl1)
#pragma config(Motor,  port7,           launcherL2,    tmotorVex393_MC29, openLoop, encoderPort, dgtl1)
#pragma config(Motor,  port8,           launcherR1,    tmotorVex393_MC29, openLoop, reversed, encoderPort, dgtl3)
#pragma config(Motor,  port9,           launcherR2,    tmotorVex393_MC29, openLoop, reversed, encoderPort, dgtl3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Competition stuff
#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(115)
#include "Vex_Competition_Includes.c"

// SmartMotorLib
#include ".\lib\SmartMotorLib.c"

// Include personal util files
#include ".\util\shooter.c"


bool shooterBool = false;
int shootSpeed = 0;
long avgBatValue;
long backupBatValue;
long expBat;
float shotMultiplier;
long finalSpeed;


void pre_auton() {
	SmartMotorsInit();
	SmartMotorPtcMonitorEnable();
	SmartMotorSetPowerExpanderStatusPort(expanderBattery);
	SmartMotorsAddPowerExtender(launcherL1, launcherL2, launcherR1, launcherR2);
	SmartMotorLinkMotors(flMotor, blMotor);
	SmartMotorLinkMotors(frMotor, brMotor);
	SmartMotorLinkMotors(launcherL1, launcherL2);
	SmartMotorLinkMotors(launcherR1, launcherR2);
	SmartMotorsSetEncoderGearing(launcherL1, 84/60);
	SmartMotorsSetEncoderGearing(launcherR2, 84/60);
	SmartMotorRun();

	wait1Msec(50);
}

task autonomous() {

}

task usercontrol()
{

	while (true) {
		SetMotor(flMotor, vexRT[Ch3]);
		SetMotor(blMotor, vexRT[Ch3]);
		SetMotor(frMotor, vexRT[Ch2]);
		SetMotor(brMotor, vexRT[Ch2]);

		if (vexRT[Btn8D])
			shooterBool = true;
		if (vexRT[Btn7D])
			shooterBool = false;

		if (shooterBool && shootSpeed < 127)
			shootSpeed = shootSpeed + 2;
		else if (shooterBool && !(shootSpeed < 127))
			shootSpeed = 127;
		else if (!shooterBool && shootSpeed > 0)
			shootSpeed--;
		else
			shootSpeed = 0;

		// 0.425 is up close

		shotMultiplier = 1;
		finalSpeed = shooterBool * shootSpeed * shotMultiplier;


		SetMotor(launcherL1, shooterBool * shootSpeed * shotMultiplier);
		SetMotor(launcherL2, shooterBool * shootSpeed * shotMultiplier);
		SetMotor(launcherR1, shooterBool * shootSpeed * shotMultiplier);
		SetMotor(launcherR2, shooterBool * shootSpeed * shotMultiplier);

		// 0.625 launcher power is full court shot



		//SmartMotorGetSpeed(launcher

		/*SwitchShooter(vexRT[Btn8D], vexRT[Btn7D], 127);

		UpdateShooter();*/

		/*avgBatValue = nAvgBatteryLevel;
		backupBatValue = BackupBatteryLevel;
		expBat = SensorValue[expanderBattery] / 300;*/

		wait1Msec(50);
	}

}
