#pragma config(Sensor, in1,    deeznutz,       sensorLineFollower)
#pragma config(Sensor, dgtl12, piston,         sensorDigitalOut)
#pragma config(Motor,  port1,           liftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           launcherL1,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           launcherL2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           launcherR1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           launcherR2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           frMotor,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           blMotor,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           flMotor,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           brMotor,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          intakeMotor,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

bool shooterBool = true;
int shootSpeed = 0;
float shotMultiplier = 0.58;
long finalSpeed;

void pre_auton(){

}

task autonomous() {
	while (true) {

		// Flywheel rampup logic
		if (shooterBool && shootSpeed < 127)
			shootSpeed = shootSpeed + 5;
		else if (shooterBool && !(shootSpeed < 127))
			shootSpeed = 127;
		else if (!shooterBool && shootSpeed > 0)
			shootSpeed--;
		else
			shootSpeed = 0;

		// Reset timer for ball launch
		if (SensorValue(deeznutz) < 2000)
			clearTimer(timer1);

		// Ramp up speed once ball goes through flywheels
		if (time1[timer1] >= 200 && time1[timer1] < 750)
			finalSpeed = shooterBool * shootSpeed * shotMultiplier * 1.1;
		else
			finalSpeed = shooterBool * shootSpeed * shotMultiplier;

		// Set motor powers
		motor[launcherL1] = finalSpeed;
		motor[launcherL2] = finalSpeed;
		motor[launcherR1] = finalSpeed;
		motor[launcherR2] = finalSpeed;

	}
}

task usercontrol() {

}
